<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StockPredictify – Prediction Result</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>

<body class="bg-gray-900 text-white flex flex-col items-center justify-center min-h-screen p-6">

    <?php
        // Dynamic color and icon logic
        $trendUp = isset($predicted) && $predicted > end($prices);
        $trendColor = $trendUp ? 'text-green-400' : 'text-red-400';
        $trendIcon = $trendUp ? '🔺' : '🔻';
    ?>

    <!-- Container -->
    <div class="bg-gray-800 rounded-2xl shadow-2xl p-8 w-full max-w-3xl text-center">

        <!-- Title -->
        <h1 class="text-3xl font-bold mb-6 flex items-center justify-center gap-3">
            <span class="<?php echo e($trendColor); ?>"><?php echo e($trendIcon); ?></span>
            <span class="<?php echo e($trendColor); ?>">📈 Prediction Result for <?php echo e(strtoupper($symbol)); ?></span>
        </h1>

        <!-- Price Summary Card -->
        <div class="bg-gray-100 text-gray-900 rounded-xl p-6 shadow-md mb-6">
            <p class="text-xl font-semibold mb-2">
                <strong>Last Recorded Price:</strong>
                ₹<?php echo e(number_format(end($prices), 2)); ?>

            </p>

            <p class="text-xl font-semibold mb-2">
                <strong>Predicted Price:</strong>
                ₹<?php echo e(number_format($predicted, 2)); ?>

            </p>

            <p class="mt-2 text-sm text-gray-600">
                Data analyzed from the last 1 month of stock movements.
            </p>
        </div>

        <!-- Flask prediction check -->
        <?php if($predicted): ?>
            <p class="text-lg mb-6 text-green-400 font-medium">
                ✅ Prediction successful — analysis generated by Stockpredictify.
            </p>
        <?php else: ?>
            <p class="text-lg mb-6 text-red-400 font-medium">
                ⚠️ Prediction unavailable (Flask server error or no data).
            </p>
        <?php endif; ?>

        <!-- Chart -->
        <canvas id="chart" width="600" height="300" class="bg-gray-700 rounded-lg p-2 shadow-inner"></canvas>

    </div>

    <!-- Chart.js -->
    <script>
    // Convert UNIX timestamps (seconds) → "Nov 12 (Tue), 2025"
    const timestamps = <?php echo json_encode($timestamps); ?>.map(ts => {
        const date = new Date(ts * 1000);
        const formattedDate = date.toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
            year: 'numeric',
            weekday: 'short'
        });
        return formattedDate;
    });

    const prices = <?php echo json_encode($prices); ?>;
    const predicted = <?php echo e($predicted ?? 'null'); ?>;
    const lastPrice = prices[prices.length - 1];
    const priceChange = predicted ? (predicted - lastPrice).toFixed(2) : 0;

    const ctx = document.getElementById('chart');
    new Chart(ctx, {
        type: 'line',
        data: {
            labels: timestamps,
            datasets: [
                {
                    label: 'Historical Price (₹)',
                    data: prices,
                    borderColor: 'rgb(75, 192, 192)',
                    backgroundColor: 'rgba(75, 192, 192, 0.15)',
                    fill: true,
                    tension: 0.35,
                    borderWidth: 2,
                    pointRadius: 3
                },
                {
                    label: 'Predicted Price (₹)',
                    data: [...prices.slice(-1), predicted],
                    borderColor: '<?php echo e(isset($predicted) && $predicted > end($prices) ? "rgb(34,197,94)" : "rgb(239,68,68)"); ?>',
                    borderDash: [6, 4],
                    borderWidth: 3,
                    pointRadius: 6,
                    tension: 0.3,
                }
            ]
        },
        options: {
            responsive: true,
            interaction: {
                mode: 'index',
                intersect: false,
            },
            plugins: {
                legend: {
                    labels: { color: '#fff' }
                },
                tooltip: {
                    backgroundColor: '#1f2937',
                    titleColor: '#fff',
                    bodyColor: '#ddd',
                    callbacks: {
                        label: function(context) {
                            const current = context.raw;
                            const previous = context.dataset.data[context.dataIndex - 1];
                            if (previous !== undefined) {
                                const diff = (current - previous).toFixed(2);
                                const change = diff >= 0 ? `↑ +${diff}` : `↓ ${diff}`;
                                return `₹${current.toFixed(2)} (${change})`;
                            }
                            return `₹${current.toFixed(2)}`;
                        }
                    }
                }
            },
            scales: {
                x: { 
                    ticks: { color: '#ccc', maxRotation: 45, minRotation: 30 },
                    grid: { color: '#444' },
                    title: { display: true, text: 'Date', color: '#aaa' }
                },
                y: { 
                    ticks: { color: '#ccc' },
                    grid: { color: '#444' },
                    title: { display: true, text: 'Stock Price (₹)', color: '#aaa' }
                }
            }
        }
    });
</script>

</body>
</html>
<?php /**PATH C:\Users\ayush\stockpredictify\resources\views/stocks/result.blade.php ENDPATH**/ ?>